#!/bin/sh

npm run lint --prefix ./backend
if [ $? -eq 0 ]
then
  echo "Pre-commit eslint check for /backend was successfull."
else
  echo "PRE-COMMIT ESLINT CHECK FAILED" && echo "Pre-commit eslint check for /backend failed. Please fix all problems with npm lint:fix script."
  exit 1
fi